sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_TOKEN
  allow-empty-commit: false
  target-branch: gh-pages
  on:
    branch: master

language: node_js

node_js:
  - 8


script:
- npm run bootstrap
- npm run build
- npm run build:doc
