environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version

  - npm install yarn -g
  - yarn install
  - yarn run bootstrap

test_script:
  - node --version
  - yarn run test:coverage

build: off
